/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYbImageRouteImport } from './routes/api/yb/image'
import { Route as ApiYbChatRouteImport } from './routes/api/yb/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYbImageRoute = ApiYbImageRouteImport.update({
  id: '/api/yb/image',
  path: '/api/yb/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYbChatRoute = ApiYbChatRouteImport.update({
  id: '/api/yb/chat',
  path: '/api/yb/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/yb/chat': typeof ApiYbChatRoute
  '/api/yb/image': typeof ApiYbImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/yb/chat': typeof ApiYbChatRoute
  '/api/yb/image': typeof ApiYbImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/yb/chat': typeof ApiYbChatRoute
  '/api/yb/image': typeof ApiYbImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/yb/chat' | '/api/yb/image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/yb/chat' | '/api/yb/image'
  id: '__root__' | '/' | '/api/yb/chat' | '/api/yb/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiYbChatRoute: typeof ApiYbChatRoute
  ApiYbImageRoute: typeof ApiYbImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yb/image': {
      id: '/api/yb/image'
      path: '/api/yb/image'
      fullPath: '/api/yb/image'
      preLoaderRoute: typeof ApiYbImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yb/chat': {
      id: '/api/yb/chat'
      path: '/api/yb/chat'
      fullPath: '/api/yb/chat'
      preLoaderRoute: typeof ApiYbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiYbChatRoute: ApiYbChatRoute,
  ApiYbImageRoute: ApiYbImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
